### ENDPOINTS PERSONAJES

### ENDPOINT QUE BUSCA TODOS LOS PERSONAJES
GET http://localhost:4000/disney/characters HTTP/1.1

### ENDPOINT QUE BUSCA UN PERSONAJE POR EL ID
GET http://localhost:4000/disney/characters/10 HTTP/1.1

### ENDPOINT QUE BUSCA UN PERSONAJE POR EL NOMBRE
GET http://localhost:4000/disney/characters/LaSirenita HTTP/1.1

### ENDPOINT QUE CREA UN PERSONAJE
POST http://localhost:4000/disney/characters/createCharacter HTTP/1.1
Content-Type: application/json
 
{
    "nombre": "gdffdfd",
    "imagen": "www.claro.com.ar",
    "edad": 67,
    "peso": 89,
    "historia": "c bc vc",
    "peliculas": "vcxvcvc"
}

### ENDPOINT QUE ACTUALIZA UN PERSONAJE
PUT http://localhost:4000/disney/characters/updateCharacter/10 HTTP/1.1
Content-Type: application/json
 
{
    "nombre": "dgdgfd",
    "imagen": "www.mercadolibre.com",
    "edad": 46,
    "peso": 78,
    "historia": "fdsvdsvdv",
    "peliculas": "dfdsds"
}

### ENDPOINT QUE ELIMINA UN PERSONAJE
DELETE http://localhost:4000/disney/characters/deleteCharacter/10 HTTP/1.1